// SPDX-License-Identifier: GPL-3.0-or-later
// Party items, phase C3 "every member keeps every item the party collects" (docs/party/items.md
// section 6): the host's item-lot awards are replayed into each guest's own world and save.
//
//   host:  the award function 0x17DDC50(MapItemMan*, lot, hostOnly) is hooked at its entry. Every
//          host-only lot (EMEVD 2003[4], Lua GetRateItem: boss drops, keys, NPC gifts) the host
//          gets in its own world becomes an ItemGrant {seq, lot, flag, ledger}. C2 progress sync
//          reports the host's item-pickup flags (treasure 5AABZnnn, key items 5000-5299) through
//          OnHostFlagSet(flag), which maps the flag back to its lot (ITEM_LOT_FLAG in
//          party_items.inc). Each grant is sent once (de-duplicated by flag / ledger index); the
//          director polls PopHostItems() and sends EVENT "items". On a (re)join the director asks
//          for TakeHostFullItems() (main thread: every lot whose flag, or whose awarding event's
//          completion flag, is set in the host's save) and sends EVENT "items_full".
//   guest: RequestGuestItems() (any thread) queues grants; ItemsTick() (main thread) applies one
//          at a time, only in the guest's own world (flag store load mode 0, own-world byte, world
//          steady, no loading screen): skip when the lot's flag (or the ledger flag
//          60009000 + idx for flagless lots) is already set, else 0x17DDC50(mim, lot, 0), which
//          rolls with the guest's own flags, gives, shows the popup and sets the lot flag; then
//          the ledger flag. Lots a guest received itself while summoned (2003[36] / hostOnly 0
//          awards, whose flag only reached the discarded overlay) are remembered and their flag
//          is set in the own world first ("mark"), so the host's later replay does not duplicate.
//   both:  optional parity patches (docs/party/items.md 5): full kill echoes, full boss clear
//          bonus and full enemy drops for clients, byte-verified, with BB_PARTY set unless
//          BB_PARTY_FULL_REWARDS=0.
//
// Env: BB_PARTY_ITEMS=0 (no hook, no replay), BB_PARTY_FULL_REWARDS=0 (no parity patches),
//      BB_PARTY_ITEMS_TEST=<lot>[,<lot>...] (debug: apply these lots once in the own world, any role).
//
// The pure part (tables, classification, JSON, queues, the apply gate) has no game dependency and
// is unit-tested (tests/test_party_items.cpp, built with BB_PARTY_ITEMS_NO_GAME).
#pragma once

#include "net/json.h"

#include <cstddef>
#include <cstdint>
#include <deque>
#include <map>
#include <optional>
#include <set>
#include <string>
#include <vector>

namespace coop {

constexpr std::int32_t kItemNone = -1;
constexpr std::uint32_t kItemLedgerBase = 60009000; ///< T6 global zone 9: saved pool, unused by the data
constexpr std::int32_t kItemLedgerSize = 1000;

enum class ItemSource : std::uint8_t {
    Unknown = 0,
    Award,  ///< host hook on 0x17DDC50 (hostOnly lot)
    Flag,   ///< host item flag reported by C2 (OnHostFlagSet)
    Full,   ///< host's full state for a (re)join
    Mark,   ///< guest-local: received while summoned, set the flag only
    Test,   ///< BB_PARTY_ITEMS_TEST
};
const char* ItemSourceName(ItemSource s);
ItemSource ItemSourceFromName(const std::string& name);

struct ItemGrant {
    std::uint64_t seq = 0;
    std::int32_t lot = kItemNone;
    std::int32_t flag = kItemNone;   ///< the lot's pickup flag (getItemFlagId), -1 if none
    std::int32_t ledger = kItemNone; ///< ledger index for flagless lots, else -1
    ItemSource source = ItemSource::Unknown;

    /// The "already given" flag a guest checks: the lot flag, or the ledger bit.
    std::int64_t DoneFlag() const;
    /// De-duplication key (one grant per flag / ledger bit).
    std::int64_t Key() const { return DoneFlag(); }
};
std::string DescribeItem(const ItemGrant& g);

// ---- Tables (party_items.inc, generated by tools/party/item_tool.py) ----
/// getItemFlagId of `lot` (rows with a flag only), else -1.
std::int32_t ItemLotFlag(std::int32_t lot);
/// The lot that owns `flag`: treasure (flag - 50,000,000 when that row has the flag), else the
/// lowest lot with that flag (alternatives share flags; the hook's capture is preferred by the
/// caller). -1 when no lot has it.
std::int32_t ItemLotForFlag(std::int32_t flag);
/// Ledger index of a flagless host-only lot, else -1.
std::int32_t ItemLedgerIndex(std::int32_t lot);
/// The completion flag of the event that awards ledger lot `idx` (host's "already awarded").
std::int32_t ItemLedgerDoneFlag(std::int32_t idx);
std::int32_t ItemLedgerLot(std::int32_t idx);
std::size_t ItemLotFlagCount();
std::size_t ItemLedgerCount();

/// Per-player or repeatable lots that are never replayed (docs/party/items.md 6.1 item 3).
bool ItemLotDenied(std::int32_t lot, std::int32_t flag);

/// Host hook: the grant for an award of `lot` (no seq yet), or nothing (client lots, denied,
/// flagless lots outside the ledger).
std::optional<ItemGrant> ClassifyAward(std::int32_t lot, bool host_only);
/// Host flag: the grant for item flag `flag`; `captured` maps flags to lots the hook saw (it
/// wins over the table for shared flags).
std::optional<ItemGrant> ClassifyFlag(std::int32_t flag, const std::map<std::int32_t, std::int32_t>& captured);

// ---- PartyLink EVENT "items" / "items_full" payload ----
constexpr const char* kItemsEventName = "items";
constexpr const char* kItemsFullEventName = "items_full";
/// {"items": [[seq, lot, flag, ledger, source], ...]} (compact: the full list has ~1000 rows).
json::Value ItemsToJson(const std::vector<ItemGrant>& items);
bool ItemsFromJson(const json::Value& v, std::vector<ItemGrant>* out, std::string* error = nullptr);
std::string ItemsToJsonText(const std::vector<ItemGrant>& items);
bool ItemsFromJsonText(const std::string& text, std::vector<ItemGrant>* out, std::string* error = nullptr);
/// Rows per event at most (the full list has ~1000; ItemsFromJson refuses more).
constexpr std::size_t kMaxItemsPerEvent = 4096;
/// May a grant the host sent reach the game (bbport security pass)? A host source (award, flag,
/// full), a lot that is not denied, and a lot / flag (or ledger row) pair the tables agree on -
/// or a lot the tables do not know with a flag that is no other lot's (a hook-captured lot;
/// GuestItems grants each such lot once). `why` says what is wrong.
bool ItemGrantFromPeerAllowed(const ItemGrant& g, std::string* why = nullptr);
/// The allowed rows of `in`; `rejected` (optional) counts the rest.
std::vector<ItemGrant> FilterPeerItems(const std::vector<ItemGrant>& in, std::size_t* rejected = nullptr);

// ---- Host ledger: what was sent ----
class HostItems {
public:
    static constexpr std::size_t kMaxQueue = 4096;
    /// Queues `g` with the next seq unless its key was offered before. True when queued.
    bool Offer(ItemGrant g);
    bool Pop(ItemGrant* out);
    std::size_t Size() const { return q_.size(); }
    /// Remembers `lot` for `flag` (hook capture), consulted by ClassifyFlag.
    void Capture(std::int32_t flag, std::int32_t lot) { captured_[flag] = lot; }
    const std::map<std::int32_t, std::int32_t>& Captured() const { return captured_; }
    std::uint64_t NextSeq() { return ++seq_; }
    void SeedSeq(std::uint64_t s) { if (s > seq_) seq_ = s; }

private:
    std::deque<ItemGrant> q_;
    std::set<std::int64_t> sent_;
    std::map<std::int32_t, std::int32_t> captured_;
    std::uint64_t seq_ = 0;
};

// ---- Guest: queue and apply gate ----
struct ItemApplyState {
    bool world_up = false;
    bool loading = false;
    int load_mode = -1;       ///< SprjEventFlagMan +0x80: 0 own world
    int own_world = -1;       ///< WorldTransitionState +0x1592: 1 own world
    int session_role = -1;    ///< SprjSessionManager +0x124
    bool game_data = false;   ///< GameDataMan +8 and the MapItemMan exist
};
/// In the own world with the flag store in mode 0, no loading screen, not joining/leaving/client.
bool ItemApplyAllowedNow(const ItemApplyState& s);

class GuestItems {
public:
    static constexpr int kStableTicks = 90;      ///< frames the gate must hold (world settled)
    static constexpr double kSpacing = 1.5;      ///< s between two awards (each opens a popup)
    static constexpr std::size_t kMaxQueue = 4096;

    /// Queues grants whose key is not queued or done yet; returns how many were taken. Marks
    /// go to the front (they must land before an item replay of the same flag).
    std::size_t Offer(const std::vector<ItemGrant>& items);
    /// Once a frame: the grant to apply now, else nothing. The caller reports Done(key) after.
    std::optional<ItemGrant> Step(const ItemApplyState& s, double now);
    void Done(std::int64_t key) { done_.insert(key); }
    std::size_t Pending() const { return q_.size(); }
    bool IsDone(std::int64_t key) const { return done_.count(key) != 0; }

private:
    std::deque<ItemGrant> q_;
    std::set<std::int64_t> queued_, done_;
    std::set<std::int32_t> adhoc_lots_;  // lots outside the tables, taken once each
    int stable_ = 0;
    double last_apply_ = -1e9;
};

#ifndef BB_PARTY_ITEMS_NO_GAME
/// bbgpu_patch_image, once, after coop::HooksInit (party mode only): the award hook and the
/// parity patches (byte-verified; a mismatch is logged and that site skipped). Registers
/// OnHostFlagSet as C2's item-flag observer (progress::SetItemFlagObserver).
void InstallItemsPatches();
/// Host: C2 reports a host item-pickup flag 0 -> 1 (any thread).
void OnHostFlagSet(std::uint32_t flag);
/// Host: the next grant to broadcast (any thread).
bool PopHostItems(ItemGrant* out);
/// Host: a member (re)joined and needs the full list (any thread; the PartyLink callback).
void RequestHostFullItems(int slot);
/// Host, main thread (the director tick): once the host's own world is up, takes one waiting
/// slot and builds its full list from the host's flags (every lot whose pickup flag, or whose
/// awarding event's completion flag, is set). False while nothing waits or the world is not up.
bool TakeHostFullItems(int* slot, std::vector<ItemGrant>* out);
/// Guest: grants from the host (any thread; the PartyLink callback).
void RequestGuestItems(const std::vector<ItemGrant>& items);
/// Main thread, once a frame (the coop tick): the guest replay.
void ItemsTick();
#endif

} // namespace coop
