// SPDX-License-Identifier: GPL-3.0-or-later
// Game id allowlists for peer validation (bbport security pass): which map, lamp / warp, entity
// and cutscene ids exist in Bloodborne 1.09. A host's travel / story / phantom events and a
// member's sign carry such ids into the other players' native code (0x13CDF30, 0x132E010,
// 0x132E050, the remo player, the summon list); an id outside these tables would make that code
// look up a param row, map or file that is not there, so it never gets there.
//
// The tables (party_ids.inc) are generated by tools/party/ids_tool.py gen-inc from the game data;
// see that tool for exactly what each one holds. Header only, no game dependency.
#pragma once

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <iterator>

namespace coop::ids {

#define PARTY_IDS_ARRAY(name, type, count) inline constexpr type name[count]
#include "party_ids.inc"
#undef PARTY_IDS_ARRAY

template <typename T, std::size_t N>
constexpr bool InSorted(const T (&table)[N], T v) {
    return std::binary_search(std::begin(table), std::end(table), v);
}

/// area << 24 | block << 16 | region << 8 | index of an existing map (folder or MSB).
inline bool MapKnown(std::uint32_t packed_map) {
    return InSorted(kPartyMaps, packed_map);
}
/// The map of an entity id AABnnnn (area AA, block B): AA << 24 | B << 16.
constexpr std::uint32_t EntityMap(std::uint32_t entity) {
    return (entity / 100000) << 24 | (entity / 10000 % 10) << 16;
}
/// A ReturnPointParam row with an existing map: an id the lamp warp 0x13CDF30 (and the last-lamp
/// / respawn records +0x1528 / +0x153C) can hold.
inline bool ReturnPointKnown(std::uint32_t id) {
    return InSorted(kPartyReturnPoints, id);
}
/// An entity id of its own map's MSB (or an EMEVD / param warp point): a warp point / bonfire id
/// 0x132E010 / 0x132E050 can be asked to place the player at.
inline bool EntityKnown(std::uint32_t id) {
    return InSorted(kPartyEntities, id);
}
/// A warp point in map `packed_map` (same area and block).
inline bool WarpPointKnown(std::uint32_t packed_map, std::uint32_t point) {
    return EntityKnown(point) && EntityMap(point) == (packed_map & 0xffff0000u);
}
/// A cutscene id with a remo/sAA_BB_NNNN.remobnd file (or one an EMEVD 2002 plays).
inline bool RemoKnown(std::uint32_t remo_id) {
    return InSorted(kPartyRemos, remo_id);
}

} // namespace coop::ids
